<?php

namespace Database\Seeders;

use App\Models\EmoDetail;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EmoDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $emo_detail = new EmoDetail();
        $emo_detail->emo_detail = "EMO000426";
        $emo_detail->manufacture = "TECO";
        $emo_detail->serial_number = "P9543291";
        $emo_detail->type = "AEEBPA040100YW05T";
        $emo_detail->power_rate = "75";
        $emo_detail->power_unit = "kW";
        $emo_detail->voltage = "380";
        $emo_detail->current_nominal = "140";
        $emo_detail->frequency = "50";
        $emo_detail->pole = "4";
        $emo_detail->rpm = "1475";
        $emo_detail->bearing_de = "NU216";
        $emo_detail->bearing_nde = "6213";
        $emo_detail->frame_type = "250 M";
        $emo_detail->shaft_diameter = 75;
        $emo_detail->phase_supply = "3";
        $emo_detail->cos_phi = "0.84";
        $emo_detail->efficiency = null;
        $emo_detail->ip_rating = "55";
        $emo_detail->insulation_class = "F";
        $emo_detail->duty = "S1";
        $emo_detail->connection_type = "Star-Delta";
        $emo_detail->nipple_grease = "Available";
        $emo_detail->greasing_type = null;
        $emo_detail->greasing_qty_de = null;
        $emo_detail->greasing_qty_nde = null;
        $emo_detail->length = null;
        $emo_detail->width = null;
        $emo_detail->height = 250;
        $emo_detail->weight = null;
        $emo_detail->cooling_fan = "Internal";
        $emo_detail->mounting = "Horizontal";
        $emo_detail->save();

        $emo_detail1 = new EmoDetail();
        $emo_detail1->emo_detail = "MGM000481";
        $emo_detail1->manufacture = "Sumitomo";
        $emo_detail1->serial_number = "M5064051";
        $emo_detail1->type = "IC-F/FB-B8";
        $emo_detail1->power_rate = "5.5";
        $emo_detail1->power_unit = "kW";
        $emo_detail1->voltage = "380";
        $emo_detail1->current_nominal = "11.5";
        $emo_detail1->frequency = "50";
        $emo_detail1->pole = "4";
        $emo_detail1->rpm = "1410";
        $emo_detail1->bearing_de = "6206";
        $emo_detail1->bearing_nde = "6206";
        $emo_detail1->frame_type = "F132S";
        $emo_detail1->phase_supply = "3";
        $emo_detail1->cos_phi = "0.84";
        $emo_detail1->efficiency = null;
        $emo_detail1->ip_rating = "44";
        $emo_detail1->insulation_class = "B";
        $emo_detail1->duty = "S1";
        $emo_detail1->connection_type = "Star-Delta";
        $emo_detail1->nipple_grease = "Not Available";
        $emo_detail1->greasing_type = null;
        $emo_detail1->greasing_qty_de = null;
        $emo_detail1->greasing_qty_nde = null;
        $emo_detail1->length = null;
        $emo_detail1->width = null;
        $emo_detail1->height = 132;
        $emo_detail1->weight = null;
        $emo_detail1->cooling_fan = "Internal";
        $emo_detail1->mounting = "Vertical";
        $emo_detail1->save();

        $emo_detail2 = new EmoDetail();
        $emo_detail2->emo_detail = "EMO001056";
        $emo_detail2->manufacture = "TECO";
        $emo_detail2->serial_number = "P9524661";
        $emo_detail2->type = "AEVB";
        $emo_detail2->power_rate = "3";
        $emo_detail2->power_unit = "kW";
        $emo_detail2->voltage = "380";
        $emo_detail2->current_nominal = "7.1";
        $emo_detail2->frequency = "50";
        $emo_detail2->pole = "4";
        $emo_detail2->rpm = "1400";
        $emo_detail2->bearing_de = "6206";
        $emo_detail2->bearing_nde = "6305";
        $emo_detail2->frame_type = "100L";
        $emo_detail2->phase_supply = "3";
        $emo_detail2->ip_rating = "55";
        $emo_detail2->insulation_class = "F";
        $emo_detail2->connection_type = "Delta";
        $emo_detail2->nipple_grease = "Not Available";
        $emo_detail2->greasing_type = null;
        $emo_detail2->greasing_qty_de = null;
        $emo_detail2->greasing_qty_nde = null;
        $emo_detail2->length = null;
        $emo_detail2->width = null;
        $emo_detail2->height = 100;
        $emo_detail2->weight = null;
        $emo_detail2->cooling_fan = "Internal";
        $emo_detail2->mounting = "Vertical";
        $emo_detail2->save();

        $emo_detail3 = new EmoDetail();
        $emo_detail3->emo_detail = "EMO004493";
        $emo_detail3->manufacture = "TMEIC";
        $emo_detail3->serial_number = "E167050HF";
        $emo_detail3->type = "IDF-CHKWII";
        $emo_detail3->power_rate = "750";
        $emo_detail3->power_unit = "kW";
        $emo_detail3->voltage = "690";
        $emo_detail3->current_nominal = "770";
        $emo_detail3->frequency = "50";
        $emo_detail3->pole = "6";
        $emo_detail3->rpm = "1150";
        $emo_detail3->bearing_de = "6228";
        $emo_detail3->bearing_nde = "6228";
        $emo_detail3->frame_type = "450";
        $emo_detail3->phase_supply = "3";
        $emo_detail3->ip_rating = "44";
        $emo_detail3->insulation_class = "F";
        $emo_detail3->connection_type = "Delta";
        $emo_detail3->nipple_grease = "Available";
        $emo_detail3->greasing_type = null;
        $emo_detail3->greasing_qty_de = null;
        $emo_detail3->greasing_qty_nde = null;
        $emo_detail3->length = null;
        $emo_detail3->width = null;
        $emo_detail3->height = 450;
        $emo_detail3->weight = null;
        $emo_detail3->cooling_fan = "Internal";
        $emo_detail3->mounting = "Horizontal";
        $emo_detail3->save();

        $emo_detail4 = new EmoDetail();
        $emo_detail4->emo_detail = "EMO003963";
        $emo_detail4->manufacture = "GE";
        $emo_detail4->serial_number = "FB8359992";
        $emo_detail4->type = "K";
        $emo_detail4->power_rate = "450";
        $emo_detail4->power_unit = "HP";
        $emo_detail4->voltage = "3000";
        $emo_detail4->current_nominal = "87.4";
        $emo_detail4->frequency = "50";
        $emo_detail4->pole = "10";
        $emo_detail4->rpm = "590";
        $emo_detail4->frame_type = "8307S";
        $emo_detail4->phase_supply = "3";
        $emo_detail4->ip_rating = "55";
        $emo_detail4->insulation_class = "F";
        $emo_detail4->nipple_grease = "Available";
        $emo_detail4->cooling_fan = "External";
        $emo_detail4->mounting = "Horizontal";
        $emo_detail4->save();

        $emo_detail5 = new EmoDetail();
        $emo_detail5->emo_detail = "EMO003604";
        $emo_detail5->manufacture = "MASTER";
        $emo_detail5->serial_number = "642058 -KM";
        $emo_detail5->type = "PB";
        $emo_detail5->power_rate = "1.5/2.2";
        $emo_detail5->power_unit = "kW";
        $emo_detail5->voltage = "380";
        $emo_detail5->current_nominal = "3.5/5.1";
        $emo_detail5->frequency = "50";
        $emo_detail5->pole = "4/16";
        $emo_detail5->rpm = "1460/230";
        $emo_detail5->phase_supply = "3";
        $emo_detail5->cos_phi = "0.86";
        $emo_detail5->nipple_grease = "Not Available";
        $emo_detail5->cooling_fan = "External";
        $emo_detail5->mounting = "Vertical";
        $emo_detail5->save();

        $emo_detail6 = new EmoDetail();
        $emo_detail6->emo_detail = "EMO001092";
        $emo_detail6->manufacture = "TECO";
        $emo_detail6->serial_number = "C104653-2";
        $emo_detail6->type = "AEJE";
        $emo_detail6->power_rate = "215";
        $emo_detail6->power_unit = "HP";
        $emo_detail6->voltage = "380";
        $emo_detail6->current_nominal = "316";
        $emo_detail6->frequency = "50";
        $emo_detail6->pole = "8";
        $emo_detail6->rpm = "735";
        $emo_detail6->bearing_de = "NU324";
        $emo_detail6->bearing_nde = "6320";
        $emo_detail6->frame_type = "315C";
        $emo_detail6->shaft_diameter = "110";
        $emo_detail6->phase_supply = "3";
        $emo_detail6->efficiency = "0.93";
        $emo_detail6->ip_rating = "55";
        $emo_detail6->insulation_class = "F";
        $emo_detail6->connection_type = "Delta";
        $emo_detail6->nipple_grease = "Available";
        $emo_detail6->length = "7110";
        $emo_detail6->width = "510";
        $emo_detail6->height = "315";
        $emo_detail6->cooling_fan = "Internal";
        $emo_detail6->mounting = "Horizontal";
        $emo_detail6->save();

        $emo_detail7 = new EmoDetail();
        $emo_detail7->emo_detail = "EMO005614";
        $emo_detail7->manufacture = "ABB";
        $emo_detail7->serial_number = "4694030";
        $emo_detail7->type = "NM 400LA4A BAFS";
        $emo_detail7->power_rate = "1100";
        $emo_detail7->power_unit = "kW";
        $emo_detail7->voltage = "690";
        $emo_detail7->current_nominal = "1080";
        $emo_detail7->frequency = "50";
        $emo_detail7->pole = "4";
        $emo_detail7->rpm = "1484";
        $emo_detail7->bearing_de = "EBKL 6226/C3";
        $emo_detail7->bearing_nde = "EBKL 6220/C3";
        $emo_detail7->frame_type = "400L";
        $emo_detail7->shaft_diameter = null;
        $emo_detail7->phase_supply = "3";
        $emo_detail7->cos_phi = "0.89";
        $emo_detail7->efficiency = null;
        $emo_detail7->ip_rating = "55";
        $emo_detail7->insulation_class = "F";
        $emo_detail7->duty = "S1";
        $emo_detail7->connection_type = "Delta";
        $emo_detail7->nipple_grease = "Available";
        $emo_detail7->greasing_type = "UNIREX N2";
        $emo_detail7->greasing_qty_de = "45";
        $emo_detail7->greasing_qty_nde = "30";
        $emo_detail7->length = null;
        $emo_detail7->width = null;
        $emo_detail7->height = null;
        $emo_detail7->weight = "3680";
        $emo_detail7->cooling_fan = "Internal";
        $emo_detail7->mounting = "Horizontal";
        $emo_detail7->save();

        $emo_detail8 = new EmoDetail();
        $emo_detail8->emo_detail = "EMO002281";
        $emo_detail8->manufacture = "TECO";
        $emo_detail8->serial_number = "P9527671";
        $emo_detail8->type = "AEEBPA";
        $emo_detail8->power_rate = "11";
        $emo_detail8->power_unit = "kW";
        $emo_detail8->voltage = "380";
        $emo_detail8->current_nominal = "21.6";
        $emo_detail8->frequency = "50";
        $emo_detail8->pole = "2";
        $emo_detail8->rpm = "2980";
        $emo_detail8->bearing_de = "6309 ZZ";
        $emo_detail8->bearing_nde = "6308 ZZ";
        $emo_detail8->frame_type = "160L";
        $emo_detail8->shaft_diameter = null;
        $emo_detail8->phase_supply = "3";
        $emo_detail8->cos_phi = null;
        $emo_detail8->efficiency = null;
        $emo_detail8->ip_rating = "54";
        $emo_detail8->insulation_class = "F";
        $emo_detail8->duty = "S1";
        $emo_detail8->connection_type = "Delta";
        $emo_detail8->nipple_grease = "Not Available";
        $emo_detail8->greasing_type = null;
        $emo_detail8->greasing_qty_de = null;
        $emo_detail8->greasing_qty_nde = null;
        $emo_detail8->length = null;
        $emo_detail8->width = null;
        $emo_detail8->height = null;
        $emo_detail8->weight = null;
        $emo_detail8->cooling_fan = "Internal";
        $emo_detail8->mounting = "Horizontal";
        $emo_detail8->save();

        $spare11kW = new EmoDetail();
        $spare11kW->emo_detail = "EMO004444";
        $spare11kW->manufacture = "ABB";
        $spare11kW->serial_number = "AEEB160L BAFS";
        $spare11kW->type = "AEEBPA";
        $spare11kW->power_rate = "11";
        $spare11kW->power_unit = "kW";
        $spare11kW->voltage = "380";
        $spare11kW->current_nominal = "21.6";
        $spare11kW->frequency = "50";
        $spare11kW->pole = "2";
        $spare11kW->rpm = "2980";
        $spare11kW->bearing_de = "6309";
        $spare11kW->bearing_nde = "6308";
        $spare11kW->frame_type = "160L";
        $spare11kW->shaft_diameter = null;
        $spare11kW->phase_supply = "3";
        $spare11kW->cos_phi = null;
        $spare11kW->efficiency = null;
        $spare11kW->ip_rating = "55";
        $spare11kW->insulation_class = "F";
        $spare11kW->duty = "S1";
        $spare11kW->connection_type = "Delta";
        $spare11kW->nipple_grease = "Not Available";
        $spare11kW->greasing_type = null;
        $spare11kW->greasing_qty_de = null;
        $spare11kW->greasing_qty_nde = null;
        $spare11kW->length = null;
        $spare11kW->width = null;
        $spare11kW->height = null;
        $spare11kW->weight = null;
        $spare11kW->cooling_fan = "Internal";
        $spare11kW->mounting = "Horizontal";
        $spare11kW->save();
    }
}
