<?php

namespace Database\Seeders;

use App\Models\TrafoDetails;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TrafoDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $trafo_detail1 = new TrafoDetails();
        $trafo_detail1->trafo_detail = 'ETF000085';
        $trafo_detail1->power_rate = '50000';
        $trafo_detail1->power_unit = 'kVA';
        $trafo_detail1->primary_voltage = '150000';
        $trafo_detail1->secondary_voltage = '20000';
        $trafo_detail1->primary_current = '192';
        $trafo_detail1->secondary_current = '1443';
        $trafo_detail1->primary_connection_type = 'Delta';
        $trafo_detail1->secondary_connection_type = 'Star';
        $trafo_detail1->frequency = '50';
        $trafo_detail1->type = 'Step down';
        $trafo_detail1->manufacturer = 'Unindo';
        $trafo_detail1->year_of_manufacture = '2012';
        $trafo_detail1->serial_number = 'P050LEC692';
        $trafo_detail1->vector_group = 'Ynyn 0 + d';
        $trafo_detail1->insulation_class = null;
        $trafo_detail1->type_of_cooling = 'ONAN/ONAF';
        $trafo_detail1->temp_rise_oil_winding = null;
        $trafo_detail1->weight = null;
        $trafo_detail1->weight_of_oil = null;
        $trafo_detail1->oil_type = null;
        $trafo_detail1->ip_rating = null;
        $trafo_detail1->created_at = Carbon::now()->toDateTimeString();
        $trafo_detail1->updated_at = Carbon::now()->toDateTimeString();
        $trafo_detail1->save();

        $trafo_detail2 = new TrafoDetails();
        $trafo_detail2->trafo_detail = 'ETF000027';
        $trafo_detail2->power_rate = '45000';
        $trafo_detail2->power_unit = 'kVA';
        $trafo_detail2->primary_voltage = '11000';
        $trafo_detail2->secondary_voltage = '20000';
        $trafo_detail2->primary_current = '2362';
        $trafo_detail2->secondary_current = '1237.2';
        $trafo_detail2->primary_connection_type = null;
        $trafo_detail2->secondary_connection_type = null;
        $trafo_detail2->frequency = '50';
        $trafo_detail2->type = 'Step up';
        $trafo_detail2->manufacturer = 'Pauwels Trafo';
        $trafo_detail2->year_of_manufacture = '1995';
        $trafo_detail2->serial_number = '94.4.6289';
        $trafo_detail2->vector_group = 'Ynd1';
        $trafo_detail2->insulation_class = null;
        $trafo_detail2->type_of_cooling = 'ONAN/ONAF 80/100%';
        $trafo_detail2->temp_rise_oil_winding = null;
        $trafo_detail2->weight = null;
        $trafo_detail2->weight_of_oil = '8800';
        $trafo_detail2->oil_type = null;
        $trafo_detail2->ip_rating = null;
        $trafo_detail2->created_at = Carbon::now()->toDateTimeString();
        $trafo_detail2->updated_at = Carbon::now()->toDateTimeString();
        $trafo_detail2->save();

        $trafo_detail3 = new TrafoDetails();
        $trafo_detail3->trafo_detail = 'ETF000060';
        $trafo_detail3->power_rate = '45000';
        $trafo_detail3->power_unit = 'kVA';
        $trafo_detail3->primary_voltage = '11000';
        $trafo_detail3->secondary_voltage = '20000';
        $trafo_detail3->primary_current = '2362.5';
        $trafo_detail3->secondary_current = '1237.2';
        $trafo_detail3->primary_connection_type = null;
        $trafo_detail3->secondary_connection_type = null;
        $trafo_detail3->frequency = '50';
        $trafo_detail3->type = 'Step up';
        $trafo_detail3->manufacturer = 'Pauwels Trafo';
        $trafo_detail3->year_of_manufacture = '2006';
        $trafo_detail3->serial_number = '510063';
        $trafo_detail3->vector_group = 'Ynd1';
        $trafo_detail3->insulation_class = null;
        $trafo_detail3->type_of_cooling = 'ONAN/ONAF 80/100%';
        $trafo_detail3->temp_rise_oil_winding = null;
        $trafo_detail3->weight = null;
        $trafo_detail3->weight_of_oil = '8470';
        $trafo_detail3->oil_type = null;
        $trafo_detail3->ip_rating = null;
        $trafo_detail3->created_at = Carbon::now()->toDateTimeString();
        $trafo_detail3->updated_at = Carbon::now()->toDateTimeString();
        $trafo_detail3->save();

        $trafo_detail4 = new TrafoDetails();
        $trafo_detail4->trafo_detail = 'ETF000026';
        $trafo_detail4->power_rate = '1000';
        $trafo_detail4->power_unit = 'kVA';
        $trafo_detail4->primary_voltage = '20000';
        $trafo_detail4->secondary_voltage = '400';
        $trafo_detail4->primary_current = '28.87';
        $trafo_detail4->secondary_current = '1443';
        $trafo_detail4->primary_connection_type = null;
        $trafo_detail4->secondary_connection_type = null;
        $trafo_detail4->frequency = '50';
        $trafo_detail4->type = 'Step down';
        $trafo_detail4->manufacturer = 'Pauwels Trafo';
        $trafo_detail4->year_of_manufacture = '1995';
        $trafo_detail4->serial_number = '3417186';
        $trafo_detail4->vector_group = 'Dyn11';
        $trafo_detail4->insulation_class = null;
        $trafo_detail4->type_of_cooling = 'ONAN';
        $trafo_detail4->temp_rise_oil_winding = null;
        $trafo_detail4->weight = null;
        $trafo_detail4->weight_of_oil = '510';
        $trafo_detail4->oil_type = null;
        $trafo_detail4->ip_rating = null;
        $trafo_detail4->created_at = Carbon::now()->toDateTimeString();
        $trafo_detail4->updated_at = Carbon::now()->toDateTimeString();
        $trafo_detail4->save();

        $trafo_detail5 = new TrafoDetails();
        $trafo_detail5->trafo_detail = 'ETF000059';
        $trafo_detail5->power_rate = '2500';
        $trafo_detail5->power_unit = 'kVA';
        $trafo_detail5->primary_voltage = '20000';
        $trafo_detail5->secondary_voltage = '400';
        $trafo_detail5->primary_current = '72.17';
        $trafo_detail5->secondary_current = '3808.44';
        $trafo_detail5->primary_connection_type = null;
        $trafo_detail5->secondary_connection_type = null;
        $trafo_detail5->frequency = '50';
        $trafo_detail5->type = 'Step down';
        $trafo_detail5->manufacturer = 'Trafindo';
        $trafo_detail5->year_of_manufacture = '2005';
        $trafo_detail5->serial_number = '5331629';
        $trafo_detail5->vector_group = 'Dyn5';
        $trafo_detail5->insulation_class = null;
        $trafo_detail5->type_of_cooling = 'ONAN';
        $trafo_detail5->temp_rise_oil_winding = null;
        $trafo_detail5->weight = null;
        $trafo_detail5->weight_of_oil = null;
        $trafo_detail5->oil_type = null;
        $trafo_detail5->ip_rating = null;
        $trafo_detail5->created_at = Carbon::now()->toDateTimeString();
        $trafo_detail5->updated_at = Carbon::now()->toDateTimeString();
        $trafo_detail5->save();

        $trafo_detail6 = new TrafoDetails();
        $trafo_detail6->trafo_detail = 'ETF000120';
        $trafo_detail6->power_rate = '3000';
        $trafo_detail6->power_unit = 'kVA';
        $trafo_detail6->primary_voltage = '20000';
        $trafo_detail6->secondary_voltage = '400';
        $trafo_detail6->primary_current = '86.6';
        $trafo_detail6->secondary_current = '4330';
        $trafo_detail6->primary_connection_type = null;
        $trafo_detail6->secondary_connection_type = null;
        $trafo_detail6->frequency = '50';
        $trafo_detail6->type = 'Step down';
        $trafo_detail6->manufacturer = 'Schneider';
        $trafo_detail6->year_of_manufacture = '2016';
        $trafo_detail6->serial_number = '33162210003';
        $trafo_detail6->vector_group = 'Dyn5';
        $trafo_detail6->insulation_class = null;
        $trafo_detail6->type_of_cooling = 'ONAN';
        $trafo_detail6->temp_rise_oil_winding = null;
        $trafo_detail6->weight = null;
        $trafo_detail6->weight_of_oil = null;
        $trafo_detail6->oil_type = null;
        $trafo_detail6->ip_rating = null;
        $trafo_detail6->created_at = Carbon::now()->toDateTimeString();
        $trafo_detail6->updated_at = Carbon::now()->toDateTimeString();
        $trafo_detail6->save();

        $trafo_detail7 = new TrafoDetails();
        $trafo_detail7->trafo_detail = 'ETF000123';
        $trafo_detail7->power_rate = '2500';
        $trafo_detail7->power_unit = 'kVA';
        $trafo_detail7->primary_voltage = '20000';
        $trafo_detail7->secondary_voltage = '400';
        $trafo_detail7->primary_current = '72.7';
        $trafo_detail7->secondary_current = '3608';
        $trafo_detail7->primary_connection_type = null;
        $trafo_detail7->secondary_connection_type = null;
        $trafo_detail7->frequency = '50';
        $trafo_detail7->type = 'Step down';
        $trafo_detail7->manufacturer = 'Schneider';
        $trafo_detail7->year_of_manufacture = '1997';
        $trafo_detail7->serial_number = '58201';
        $trafo_detail7->vector_group = 'Dyn5';
        $trafo_detail7->insulation_class = null;
        $trafo_detail7->type_of_cooling = 'ESSO 80';
        $trafo_detail7->temp_rise_oil_winding = null;
        $trafo_detail7->weight = null;
        $trafo_detail7->weight_of_oil = '5750';
        $trafo_detail7->oil_type = null;
        $trafo_detail7->ip_rating = null;
        $trafo_detail7->created_at = Carbon::now()->toDateTimeString();
        $trafo_detail7->updated_at = Carbon::now()->toDateTimeString();
        $trafo_detail7->save();

        $trafo_detail8 = new TrafoDetails();
        $trafo_detail8->trafo_detail = 'ETF000006';
        $trafo_detail8->power_rate = '3000';
        $trafo_detail8->power_unit = 'kVA';
        $trafo_detail8->primary_voltage = '20000';
        $trafo_detail8->secondary_voltage = '400';
        $trafo_detail8->primary_current = '86.6';
        $trafo_detail8->secondary_current = '4330.1';
        $trafo_detail8->primary_connection_type = null;
        $trafo_detail8->secondary_connection_type = null;
        $trafo_detail8->frequency = '50';
        $trafo_detail8->type = 'Step down';
        $trafo_detail8->manufacturer = 'Trafindo';
        $trafo_detail8->year_of_manufacture = '2010';
        $trafo_detail8->serial_number = '10338949';
        $trafo_detail8->vector_group = 'Dyn5';
        $trafo_detail8->insulation_class = null;
        $trafo_detail8->type_of_cooling = 'ONAN';
        $trafo_detail8->temp_rise_oil_winding = null;
        $trafo_detail8->weight = null;
        $trafo_detail8->weight_of_oil = null;
        $trafo_detail8->oil_type = null;
        $trafo_detail8->ip_rating = null;
        $trafo_detail8->created_at = Carbon::now()->toDateTimeString();
        $trafo_detail8->updated_at = Carbon::now()->toDateTimeString();
        $trafo_detail8->save();

        $trafo_detail9 = new TrafoDetails();
        $trafo_detail9->trafo_detail = 'ETF000032';
        $trafo_detail9->power_rate = '2500';
        $trafo_detail9->power_unit = 'kVA';
        $trafo_detail9->primary_voltage = '20000';
        $trafo_detail9->secondary_voltage = '400';
        $trafo_detail9->primary_current = '72.1';
        $trafo_detail9->secondary_current = '3608.4';
        $trafo_detail9->primary_connection_type = null;
        $trafo_detail9->secondary_connection_type = null;
        $trafo_detail9->frequency = '50';
        $trafo_detail9->type = 'Step down';
        $trafo_detail9->manufacturer = 'Unindo';
        $trafo_detail9->year_of_manufacture = '1994';
        $trafo_detail9->serial_number = '60952';
        $trafo_detail9->vector_group = 'Dyn5';
        $trafo_detail9->insulation_class = null;
        $trafo_detail9->type_of_cooling = 'ONAN';
        $trafo_detail9->temp_rise_oil_winding = null;
        $trafo_detail9->weight = null;
        $trafo_detail9->weight_of_oil = '5750';
        $trafo_detail9->oil_type = null;
        $trafo_detail9->ip_rating = null;
        $trafo_detail9->created_at = Carbon::now()->toDateTimeString();
        $trafo_detail9->updated_at = Carbon::now()->toDateTimeString();
        $trafo_detail9->save();

        $trafo_detail10 = new TrafoDetails();
        $trafo_detail10->trafo_detail = 'ETF000091';
        $trafo_detail10->power_rate = '55000';
        $trafo_detail10->power_unit = 'kVA';
        $trafo_detail10->primary_voltage = '380';
        $trafo_detail10->secondary_voltage = '66000';
        $trafo_detail10->primary_current = null;
        $trafo_detail10->secondary_current = null;
        $trafo_detail10->primary_connection_type = null;
        $trafo_detail10->secondary_connection_type = null;
        $trafo_detail10->frequency = '50';
        $trafo_detail10->type = 'Step up';
        $trafo_detail10->manufacturer = 'Fujian Longking';
        $trafo_detail10->year_of_manufacture = '2011';
        $trafo_detail10->serial_number = '2011466';
        $trafo_detail10->vector_group = 'Dyn5';
        $trafo_detail10->insulation_class = null;
        $trafo_detail10->type_of_cooling = 'ONAN';
        $trafo_detail10->temp_rise_oil_winding = null;
        $trafo_detail10->weight = null;
        $trafo_detail10->weight_of_oil = '5750';
        $trafo_detail10->oil_type = null;
        $trafo_detail10->ip_rating = null;
        $trafo_detail10->created_at = Carbon::now()->toDateTimeString();
        $trafo_detail10->updated_at = Carbon::now()->toDateTimeString();
        $trafo_detail10->save();
    }
}
