USE fajar_e_maintenance;
DROP DATABASE fajar_e_maintenance;
SHOW TABLES;
SELECT * FROM migrations;
DELETE FROM users;
SELECT * FROM users;
SELECT * FROM emos;
SELECT * FROM emo_details;
SHOW CREATE TABLE users;
SHOW CREATE TABLE emos;
SHOW CREATE TABLE function_locations;
SHOW CREATE TABLE emo_details;
